# Materials list - http://jd.bukkit.org/apidocs/org/bukkit/Material.html
#
# Example of item craft
#
# Recipes:
#    MeteorStormSkill:
#        DisplayName: Meteor
#        Output: WRITTEN_BOOK
#        Amount: 1
##        /\ Can remove and will default to 1
##        DisplayName, BookAuthor, and BookPages support color codes - Example &4 is dark red
#        BookAuthor: BrokenWorlds
#        BookPages: BrokenWorlds Meteor&pPage Test
##        /\ Add &p for a new page!
#        Characters:
#         - A
#         - B
#         - C
#         - D
#        CharactersMaterials:
#         - EMERALD
#         - GOLD_BLOCK
#         - FIREBALL
#         - BOOK_AND_QUILL
##        Characters correspond to their Material so A = Emerald
#        TopRow: ABA
#        Middle: CDC
#        Bottom: ABA